var tigger = {character: "Tiger"}
var piglet = {character: "Piglet"}
var pooh = {character:"winnie the pooh"}
var bees = {character: "bees"}
var owl = {character:"owl"}
var christopher = {character: "christopher Robin"}
var rabbit = {character: "Rabbit"}
var gopher = {character: "Gopher"}
var Kanga = {character: "Kanga"}
var eeyore = {character: "Eeyore"}
var heffalumps = {character: "Heffalumps"}

tigger.north = pooh
piglet.north = owl
piglet.east = pooh
pooh.west = piglet
pooh.north = christopher
pooh.west = bees
pooh.south = tigger
bees.north = rabbit
bees.west = pooh
owl.south = piglet
owl.east = christopher
christopher.north = Kanga
christopher.east = rabbit
christopher.south = pooh
christopher.west = owl
rabbit.west = christopher
rabbit.east = gopher
rabbit.south = bees
gopher.west = rabbit
kanga.south = christopher
kanga.north = eeyore
eeyore.south = kanga
eeyore.east = heffalumps